export const REQUEST_FEATCH_BANNERS = "REQUEST_FEATCH_BANNERS"
export const SUCCESS_FEATCH_BANNERS = "SUCCESS_FEATCH_BANNERS"
export const    FAIL_FEATCH_BANNERS    = "FAIL_FEATCH_BANNERS"
export const CLEAR_ERRORS    = "CLEAR_ERRORS"