export const FETCH_ADDRESS_FORM = "FETCH_ADDRESS_FORM"
export const FETCH_ADDRESS_FORM_SUCCESS = "FETCH_ADDRESS_FORM_SUCCESS"
export const FETCH_ADDRESS_FORM_FAIL = "FETCH_ADDRESS_FORM_FAIL"
export const CLEAR_ERRORS    = "CLEAR_ERRORS"


export const FETCH_ALL_OPTIONS_REQUEST = "FETCH_ALL_OPTIONS_REQUEST";
export const FETCH_ALL_OPTIONS_SUCCESS = "FETCH_ALL_OPTIONS_SUCCESS";
export const FETCH_ALL_OPTIONS_FAIL = "FETCH_ALL_OPTIONS_FAIL";



export const FETCH_ALL_COUPONS_REQUEST = "FETCH_ALL_COUPONS_REQUEST";
export const FETCH_ALL_COUPONS_SUCCESS = "FETCH_ALL_COUPONS_SUCCESS";
export const FETCH_ALL_COUPONS_FAIL = "FETCH_ALL_COUPONS_FAIL";
