export const FETCH_ADDRESS_FORM = "FETCH_ADDRESS_FORM"
export const FETCH_ADDRESS_FORM_SUCCESS = "FETCH_ADDRESS_FORM_SUCCESS"
export const FETCH_ADDRESS_FORM_FAIL = "FETCH_ADDRESS_FORM_FAIL"
export const CLEAR_ERRORS    = "CLEAR_ERRORS   "